<a href="https://colab.research.google.com/github/cennetbakici/introduction-to-machine-learning/blob/main/Gaihub_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr_1 = np.array([1,2,3,4,5])
arr_1

array([1, 2, 3, 4, 5])

In [ ]:
arr_2 = np.array([[1,2,3,4],
                 [5,6,7,8]])
arr_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])